model = "gpt-5.2-codex"
model_reasoning_effort = "high"
approval_policy = "on-request"
hide_agent_reasoning = true
sandbox_mode = "workspace-write"
network_access = true

notify = ["bash", "-c", "source $HOME/.codex/notify.sh"]
personality = "pragmatic"

[tui]
notifications = [
  "agent-turn-complete",
  "approval-requested"
]

[features]
skills = true
web_search_request = true

[mcp_servers.serena]
command = "uvx"
args = [
  "--from", "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context", "codex",
  "--enable-web-dashboard", "False",
]

[mcp_servers.phpstorm]
command = "npx"
args = [
  "mcp-remote",
  "http://localhost:64342/sse"
]

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
